# Generated by Django 5.2.12 on 2026-04-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_papertrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
