# Generated by Django 5.2.12 on 2026-04-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
