# Generated by Django 5.2.12 on 2026-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
